-- Snowflake SQL Boilerplate
-- Replace object names and credentials with your environment values.
-- Sections: Session context, DDL, File formats, Stage, Load, Queries, Views, DML, Time Travel, Task.

-- 1. Session and current context
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MY_WH;
USE DATABASE MY_DB;
USE SCHEMA PUBLIC;

-- 2. Create database, warehouse, schema
CREATE OR REPLACE WAREHOUSE MY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE MY_DB;
CREATE OR REPLACE SCHEMA IF NOT EXISTS MY_DB.PUBLIC;

-- 3. Create a file format
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('NULL', 'null');

-- 4. Create a table
CREATE OR REPLACE TABLE MY_DB.PUBLIC.CUSTOMERS (
  CUSTOMER_ID INT AUTOINCREMENT,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING DEFAULT 'ACTIVE'
);

-- 5. Create an internal stage for data load
CREATE OR REPLACE STAGE MY_DB.PUBLIC.MY_STAGE
  FILE_FORMAT = MY_CSV_FORMAT;

-- 6. Load data into table from stage
COPY INTO MY_DB.PUBLIC.CUSTOMERS
  FROM @MY_DB.PUBLIC.MY_STAGE/customers/
  FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
  ON_ERROR = 'CONTINUE'
  FORCE = FALSE
  PURGE = FALSE;

-- 7. Basic query examples
SELECT CUSTOMER_ID,
       FIRST_NAME,
       LAST_NAME,
       EMAIL,
       CREATED_AT
FROM MY_DB.PUBLIC.CUSTOMERS
WHERE CREATED_AT >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY CREATED_AT DESC;

-- 8. Create a view
CREATE OR REPLACE VIEW MY_DB.PUBLIC.CUSTOMER_SUMMARY AS
SELECT COUNT(*) AS TOTAL_CUSTOMERS,
       COUNT_IF(STATUS = 'ACTIVE') AS ACTIVE_CUSTOMERS,
       MIN(CREATED_AT) AS FIRST_SIGNUP,
       MAX(CREATED_AT) AS LAST_SIGNUP
FROM MY_DB.PUBLIC.CUSTOMERS;

-- 9. Insert, update, delete examples
INSERT INTO MY_DB.PUBLIC.CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Jane', 'Doe', 'jane.doe@example.com');

UPDATE MY_DB.PUBLIC.CUSTOMERS
SET EMAIL = 'jane.doe@newdomain.com'
WHERE CUSTOMER_ID = 1;

DELETE FROM MY_DB.PUBLIC.CUSTOMERS
WHERE CREATED_AT < DATEADD(year, -1, CURRENT_DATE());

-- 10. Time travel / cloning example
CREATE OR REPLACE TABLE MY_DB.PUBLIC.CUSTOMERS_CLONE CLONE MY_DB.PUBLIC.CUSTOMERS AT (OFFSET => -3600);

SELECT *
FROM MY_DB.PUBLIC.CUSTOMERS_CLONE
LIMIT 10;

-- 11. Create a scheduled task (enable after creating)
CREATE OR REPLACE TASK MY_DB.PUBLIC.LOAD_CUSTOMERS_TASK
  WAREHOUSE = MY_WH
  SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
  COPY INTO MY_DB.PUBLIC.CUSTOMERS
    FROM @MY_DB.PUBLIC.MY_STAGE/customers/
    FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
    ON_ERROR = 'CONTINUE';

-- To start the task:
-- ALTER TASK MY_DB.PUBLIC.LOAD_CUSTOMERS_TASK RESUME;
-- To stop the task:
-- ALTER TASK MY_DB.PUBLIC.LOAD_CUSTOMERS_TASK SUSPEND;

-- 12. Useful metadata queries
SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE MY_DB;
DESCRIBE TABLE MY_DB.PUBLIC.CUSTOMERS;
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_CATALOG = 'MY_DB';
